version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    volumes:
      - redis-data:/data
    depends_on:
      - redis
    deploy:
      replicas: 4
    ports:
      - "8080:8080"
    restart: always

volumes:
  redis-data:
