version: "3.8"

services:
  app:
    build: .
    container_name: nietzsche
    ports:
      - "8080:8080" # Adjust based on your app
    volumes:
      - .:/app # Syncs local files with the container
    working_dir: /app
    command: ["air", "-c", ".air.toml"]
